### ISSUE TITLE
Compatibility with js-Controller 6.x

### ISSUE THREAD

**Issue by TMHEINE** [bondrogeen/iobroker.paw#52]
Has anyone else Problems with js-controller Verison 6.x?
Here is the error list:

`<html><body>

host.raspberrypi | 2024-06-14 13:12:36.191 | error | instance system.adapter.paw.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.raspberrypi | 2024-06-14 13:12:36.191 | error | Caught by controller[0]: Node.js v18.20.3
host.raspberrypi | 2024-06-14 13:12:36.191 | error | Caught by controller[0]:     at node:internal/main/run_main_module:28:49
host.raspberrypi | 2024-06-14 13:12:36.191 | error | Caught by controller[0]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
host.raspberrypi | 2024-06-14 13:12:36.191 | error | Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:1019:12)
host.raspberrypi | 2024-06-14 13:12:36.191 | error | Caught by controller[0]:     at Module.load (node:internal/modules/cjs/loader:1203:32)
host.raspberrypi | 2024-06-14 13:12:36.191 | error | Caught by controller[0]:     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
host.raspberrypi | 2024-06-14 13:12:36.191 | error | Caught by controller[0]:     at Module._compile (node:internal/modules/cjs/loader:1364:14)
host.raspberrypi | 2024-06-14 13:12:36.191 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.paw/main.js:495:3)
host.raspberrypi | 2024-06-14 13:12:36.191 | error | Caught by controller[0]:     at startAdapter (/opt/iobroker/node_modules/iobroker.paw/main.js:30:13)
host.raspberrypi | 2024-06-14 13:12:36.191 | error | Caught by controller[0]: TypeError: utils.Adapter is not a constructor
host.raspberrypi | 2024-06-14 13:12:36.191 | error | Caught by controller[0]:             ^
host.raspberrypi | 2024-06-14 13:12:36.191 | error | Caught by controller[0]:   adapter = new utils.Adapter(options);
host.raspberrypi | 2024-06-14 13:12:36.191 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.paw/main.js:30
host.raspberrypi | 2024-06-14 13:12:35.804 | info | instance system.adapter.paw.0 started with pid 2636

</body>
</html>`

Is there anything I can do expect change back to js-controller v5.x?

**Comment by mcm1957** [comment]
Adapter has outdated deps and is incompatible with js controller 6.
@mcm1957
